#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number
show_client:
  path: /show_client/{id}
  controller: App\Controller\ClientController::showClient
show_all_clients:
  path: /show_all_clients
  controller: App\Controller\ClientController::showAll