#index:
#    path: /
#    controller: App\Controller\DefaultController::index

show_client:
  path: /show_client/{id}
  controller: App\Controller\ClientViewController::showClient
show_all_clients:
  path: /show_all_clients
  controller: App\Controller\ClientViewController::showAll
new_produit:
  path: /new_produit
  controller: App\Controller\ProduitController::new
show_all_produits:
  path: /show_all_produits
  controller: App\Controller\ProduitController::showAll